controller_manager:
  ros__parameters:
    update_rate: 1000  # Hz

    bmark_duration_broadcaster:
      type: bmark_controllers/DurationBroadcaster

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
